var annotated_dup =
[
    [ "IoT", "namespaceIoT.html", "namespaceIoT" ],
    [ "Poco", "namespacePoco.html", "namespacePoco" ],
    [ "AbstractEventMonitor", "classAbstractEventMonitor.html", "classAbstractEventMonitor" ],
    [ "CRYPTO_dynlock_value", "structCRYPTO__dynlock__value.html", "structCRYPTO__dynlock__value" ],
    [ "gz_header_s", "structgz__header__s.html", "structgz__header__s" ],
    [ "gzFile_s", "structgzFile__s.html", "structgzFile__s" ],
    [ "MQTTAsync_connectOptions", "structMQTTAsync__connectOptions.html", "structMQTTAsync__connectOptions" ],
    [ "MQTTAsync_createOptions", "structMQTTAsync__createOptions.html", "structMQTTAsync__createOptions" ],
    [ "MQTTAsync_disconnectOptions", "structMQTTAsync__disconnectOptions.html", "structMQTTAsync__disconnectOptions" ],
    [ "MQTTAsync_failureData", "structMQTTAsync__failureData.html", "structMQTTAsync__failureData" ],
    [ "MQTTAsync_message", "structMQTTAsync__message.html", "structMQTTAsync__message" ],
    [ "MQTTAsync_nameValue", "structMQTTAsync__nameValue.html", "structMQTTAsync__nameValue" ],
    [ "MQTTAsync_responseOptions", "structMQTTAsync__responseOptions.html", "structMQTTAsync__responseOptions" ],
    [ "MQTTAsync_SSLOptions", "structMQTTAsync__SSLOptions.html", "structMQTTAsync__SSLOptions" ],
    [ "MQTTAsync_successData", "structMQTTAsync__successData.html", "structMQTTAsync__successData" ],
    [ "MQTTAsync_willOptions", "structMQTTAsync__willOptions.html", "structMQTTAsync__willOptions" ],
    [ "MQTTClient_connectOptions", "structMQTTClient__connectOptions.html", "structMQTTClient__connectOptions" ],
    [ "MQTTClient_message", "structMQTTClient__message.html", "structMQTTClient__message" ],
    [ "MQTTClient_nameValue", "structMQTTClient__nameValue.html", "structMQTTClient__nameValue" ],
    [ "MQTTClient_persistence", "structMQTTClient__persistence.html", "structMQTTClient__persistence" ],
    [ "MQTTClient_SSLOptions", "structMQTTClient__SSLOptions.html", "structMQTTClient__SSLOptions" ],
    [ "MQTTClient_willOptions", "structMQTTClient__willOptions.html", "structMQTTClient__willOptions" ],
    [ "poco_static_assert_test", "structpoco__static__assert__test.html", null ],
    [ "POCO_STATIC_ASSERTION_FAILURE", "structPOCO__STATIC__ASSERTION__FAILURE.html", null ],
    [ "POCO_STATIC_ASSERTION_FAILURE< true >", "structPOCO__STATIC__ASSERTION__FAILURE_3_01true_01_4.html", "structPOCO__STATIC__ASSERTION__FAILURE_3_01true_01_4" ],
    [ "XML_cp", "structXML__cp.html", "structXML__cp" ],
    [ "XML_Encoding", "structXML__Encoding.html", "structXML__Encoding" ],
    [ "XML_Expat_Version", "structXML__Expat__Version.html", "structXML__Expat__Version" ],
    [ "XML_Feature", "structXML__Feature.html", "structXML__Feature" ],
    [ "XML_Memory_Handling_Suite", "structXML__Memory__Handling__Suite.html", "structXML__Memory__Handling__Suite" ],
    [ "XML_ParsingStatus", "structXML__ParsingStatus.html", "structXML__ParsingStatus" ],
    [ "z_stream_s", "structz__stream__s.html", "structz__stream__s" ]
];