var namespacePoco_1_1Zip =
[
    [ "Add", "classPoco_1_1Zip_1_1Add.html", "classPoco_1_1Zip_1_1Add" ],
    [ "AutoDetectInputStream", "classPoco_1_1Zip_1_1AutoDetectInputStream.html", "classPoco_1_1Zip_1_1AutoDetectInputStream" ],
    [ "AutoDetectIOS", "classPoco_1_1Zip_1_1AutoDetectIOS.html", "classPoco_1_1Zip_1_1AutoDetectIOS" ],
    [ "AutoDetectStreamBuf", "classPoco_1_1Zip_1_1AutoDetectStreamBuf.html", "classPoco_1_1Zip_1_1AutoDetectStreamBuf" ],
    [ "Compress", "classPoco_1_1Zip_1_1Compress.html", "classPoco_1_1Zip_1_1Compress" ],
    [ "Decompress", "classPoco_1_1Zip_1_1Decompress.html", "classPoco_1_1Zip_1_1Decompress" ],
    [ "Delete", "classPoco_1_1Zip_1_1Delete.html", "classPoco_1_1Zip_1_1Delete" ],
    [ "Keep", "classPoco_1_1Zip_1_1Keep.html", "classPoco_1_1Zip_1_1Keep" ],
    [ "ParseCallback", "classPoco_1_1Zip_1_1ParseCallback.html", "classPoco_1_1Zip_1_1ParseCallback" ],
    [ "PartialInputStream", "classPoco_1_1Zip_1_1PartialInputStream.html", "classPoco_1_1Zip_1_1PartialInputStream" ],
    [ "PartialIOS", "classPoco_1_1Zip_1_1PartialIOS.html", "classPoco_1_1Zip_1_1PartialIOS" ],
    [ "PartialOutputStream", "classPoco_1_1Zip_1_1PartialOutputStream.html", "classPoco_1_1Zip_1_1PartialOutputStream" ],
    [ "PartialStreamBuf", "classPoco_1_1Zip_1_1PartialStreamBuf.html", "classPoco_1_1Zip_1_1PartialStreamBuf" ],
    [ "Rename", "classPoco_1_1Zip_1_1Rename.html", "classPoco_1_1Zip_1_1Rename" ],
    [ "Replace", "classPoco_1_1Zip_1_1Replace.html", "classPoco_1_1Zip_1_1Replace" ],
    [ "SkipCallback", "classPoco_1_1Zip_1_1SkipCallback.html", "classPoco_1_1Zip_1_1SkipCallback" ],
    [ "ZipArchive", "classPoco_1_1Zip_1_1ZipArchive.html", "classPoco_1_1Zip_1_1ZipArchive" ],
    [ "ZipArchiveInfo", "classPoco_1_1Zip_1_1ZipArchiveInfo.html", "classPoco_1_1Zip_1_1ZipArchiveInfo" ],
    [ "ZipCommon", "classPoco_1_1Zip_1_1ZipCommon.html", "classPoco_1_1Zip_1_1ZipCommon" ],
    [ "ZipDataInfo", "classPoco_1_1Zip_1_1ZipDataInfo.html", "classPoco_1_1Zip_1_1ZipDataInfo" ],
    [ "ZipFileInfo", "classPoco_1_1Zip_1_1ZipFileInfo.html", "classPoco_1_1Zip_1_1ZipFileInfo" ],
    [ "ZipInputStream", "classPoco_1_1Zip_1_1ZipInputStream.html", "classPoco_1_1Zip_1_1ZipInputStream" ],
    [ "ZipIOS", "classPoco_1_1Zip_1_1ZipIOS.html", "classPoco_1_1Zip_1_1ZipIOS" ],
    [ "ZipLocalFileHeader", "classPoco_1_1Zip_1_1ZipLocalFileHeader.html", "classPoco_1_1Zip_1_1ZipLocalFileHeader" ],
    [ "ZipManipulator", "classPoco_1_1Zip_1_1ZipManipulator.html", "classPoco_1_1Zip_1_1ZipManipulator" ],
    [ "ZipOperation", "classPoco_1_1Zip_1_1ZipOperation.html", "classPoco_1_1Zip_1_1ZipOperation" ],
    [ "ZipOutputStream", "classPoco_1_1Zip_1_1ZipOutputStream.html", "classPoco_1_1Zip_1_1ZipOutputStream" ],
    [ "ZipStreamBuf", "classPoco_1_1Zip_1_1ZipStreamBuf.html", "classPoco_1_1Zip_1_1ZipStreamBuf" ],
    [ "ZipUtil", "classPoco_1_1Zip_1_1ZipUtil.html", "classPoco_1_1Zip_1_1ZipUtil" ]
];